### ISSUE TITLE
Getting 404 error page on appending /expand or /search to the landing page url of all dictionaries

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/glossary-app#225] opened 2020-12-31 03:17 UTC
### Issue description

> **ESTIMATE** TBD

Getting 404 error page with the text "The requested page could not be found." on appending /expand or /search to the landing page url of all dictionaries

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/publications/dictionaries/cancer-terms/expand
2. An error page is returned
3. Go to https://www.cancer.gov/publications/dictionaries/cancer-terms/search
4. An error page is returned
5. Go to https://www.cancer.gov/publications/dictionaries/genetics-dictionary/expand
6. An error page is returned
7. Go to https://www.cancer.gov/publications/dictionaries/genetics-dictionary/search
8. An error page is returned
9. Go to https://www.cancer.gov/publications/dictionaries/cancer-drug/expand 
10. An error page is returned (See https://github.com/NCIOCPL/drug-dictionary-app/issues/100)
11. Go to https://www.cancer.gov/publications/dictionaries/cancer-drug/search 
12. An error page is returned ((https://github.com/NCIOCPL/drug-dictionary-app/issues/100)

### What's the expected result?
- When user has entered /publications/dictionaries/cancer-terms/search in the URLand tries to go to this URL, system should return the "No Matches Found" page (See https://github.com/NCIOCPL/glossary-app/issues/14)
- When user appends "/expand" to the URL and tries to go to this URL, system should return the "No Matches Found" page (See https://github.com/NCIOCPL/glossary-app/issues/33)

### What's the actual result?
- The 404 page with the text "The requested page could not be found." appears.

Note: Getting the same error for https://www.cancer.gov/asdfg and https://www.cancer.gov/about-cancer/understanding/what-is-cancer/fff

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/103392545-6ad4cb80-4aec-11eb-933b-8c1d807c7088.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment] 2021-01-04 15:12
@alinai - The `expand` and `search` paths both require a value to expand or search.  You didn't specify one.

If there's a specific requirement for how the application should behave in that circumstance, please list it as the "expected result". A link to the overall requirements are fine for _additional_ explanation, but not particularly helpful for "this is what's wrong."

Thanks.

**Comment by KateMashkinaNIH** [comment] 2021-01-04 15:52
@blairlearn I suspect this is an issue not related to an app - I verified in react-app and it is behaving as expected ( e.g. 'No Matches Found' page is displayed for both URL https://react-app-dev.cancer.gov/glossary-app/develop/expand and https://react-app-dev.cancer.gov/glossary-app/develop/search)

**Comment by blairlearn** [comment] 2021-01-04 16:54
OK, so the expected behavior is a "No Matches Found" message? That's the detail I was looking for. 😀

The 404 message appears on both prod, and also lower tiers (e.g. www-dev-ac). This may not be an issue with the JavaScript application.....

Daggone it. I think this is another edge case with the Akamai configuration.

**Comment by bryanpizzillo** [comment] 2021-01-04 18:07
@VictoriaSunNIH or @lburack What say you all? I think /expand by itself should be a 404.

**Comment by bryanpizzillo** [comment] 2021-01-04 18:12
I see, this now links to the original ticket #14 which says that.

**Comment by VictoriaSunNIH** [comment] 2021-01-04 18:52
@bryanpizzillo  - so the original AC says it goes to no matches found (#14 and #33 ) and it looks like @blairlearn fixed it via Akamai...can we close this out now?

**Comment by blairlearn** [comment] 2021-01-04 19:08
Closing it now.

**Closed by blairlearn** 2021-01-04 19:08 UTC
Labels: bug
